# iOS Test Workflow
# Runs unit and UI tests on iOS simulators
# Supports multiple iOS versions and device types

name: iOS Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'ios/**'
      - '.github/workflows/ios-test.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'ios/**'
  workflow_dispatch:
    inputs:
      ios_version:
        description: 'iOS version to test'
        required: false
        default: '17.2'
      device:
        description: 'Simulator device'
        required: false
        default: 'iPhone 15'

env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
  # Update these for your project
  SCHEME: CraftApp
  PROJECT_PATH: ios/CraftApp.xcodeproj
  # Or use workspace:
  # WORKSPACE_PATH: ios/CraftApp.xcworkspace

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: macos-14
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          - ios: '17.2'
            device: 'iPhone 15'
          - ios: '16.4'
            device: 'iPhone 14'
          # Add more combinations as needed

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        if: hashFiles('ios/Podfile') != ''
        run: |
          cd ios
          pod install --repo-update

      - name: Cache Swift Package Manager
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('ios/**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Run Unit Tests
        run: |
          set -o pipefail
          xcodebuild test \
            -project "$PROJECT_PATH" \
            -scheme "$SCHEME" \
            -destination "platform=iOS Simulator,OS=${{ matrix.ios }},name=${{ matrix.device }}" \
            -resultBundlePath TestResults-${{ matrix.ios }}.xcresult \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty --color --report junit --output TestResults-${{ matrix.ios }}.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-ios-${{ matrix.ios }}
          path: |
            TestResults-${{ matrix.ios }}.xcresult
            TestResults-${{ matrix.ios }}.xml
          retention-days: 14

      - name: Generate Coverage Report
        if: success()
        run: |
          xcrun xccov view --report --json TestResults-${{ matrix.ios }}.xcresult > coverage-${{ matrix.ios }}.json
          echo "## Coverage Summary" >> $GITHUB_STEP_SUMMARY
          cat coverage-${{ matrix.ios }}.json | jq -r '.targets[] | "- \(.name): \(.lineCoverage * 100 | floor)%"' >> $GITHUB_STEP_SUMMARY

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: coverage-ios-${{ matrix.ios }}
          path: coverage-${{ matrix.ios }}.json
          retention-days: 14

  ui-tests:
    name: UI Tests
    runs-on: macos-14
    timeout-minutes: 45
    needs: unit-tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        if: hashFiles('ios/Podfile') != ''
        run: |
          cd ios
          pod install --repo-update

      - name: Boot Simulator
        run: |
          DEVICE_ID=$(xcrun simctl list devices available --json | jq -r '.devices["com.apple.CoreSimulator.SimRuntime.iOS-17-2"][] | select(.name == "iPhone 15") | .udid' | head -1)
          xcrun simctl boot "$DEVICE_ID" || true
          # Wait for simulator to be ready
          sleep 10

      - name: Run UI Tests
        run: |
          set -o pipefail
          xcodebuild test \
            -project "$PROJECT_PATH" \
            -scheme "${SCHEME}UITests" \
            -destination "platform=iOS Simulator,OS=17.2,name=iPhone 15" \
            -resultBundlePath UITestResults.xcresult \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty --color --report junit --output UITestResults.xml

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-results
          path: |
            UITestResults.xcresult
            UITestResults.xml
          retention-days: 14

      - name: Capture Screenshots on Failure
        if: failure()
        run: |
          mkdir -p screenshots
          xcrun simctl io booted screenshot screenshots/failure-$(date +%s).png

      - name: Upload Failure Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failure-screenshots
          path: screenshots/
          retention-days: 7

  snapshot-tests:
    name: Snapshot Tests
    runs-on: macos-14
    timeout-minutes: 30
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        if: hashFiles('ios/Podfile') != ''
        run: |
          cd ios
          pod install --repo-update

      - name: Run Snapshot Tests
        run: |
          set -o pipefail
          xcodebuild test \
            -project "$PROJECT_PATH" \
            -scheme "${SCHEME}SnapshotTests" \
            -destination "platform=iOS Simulator,OS=17.2,name=iPhone 15" \
            -resultBundlePath SnapshotTestResults.xcresult \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty --color

      - name: Upload Snapshot Differences
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: snapshot-differences
          path: |
            ios/**/FailureDiffs/
            SnapshotTestResults.xcresult
          retention-days: 14

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [unit-tests, ui-tests]
    if: always()

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate Summary
        run: |
          echo "## iOS Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -d "artifacts" ]; then
            echo "### Test Artifacts" >> $GITHUB_STEP_SUMMARY
            find artifacts -name "*.xml" -exec echo "- {}" \; >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Jobs Status" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Unit Tests | ${{ needs.unit-tests.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| UI Tests | ${{ needs.ui-tests.result }} |" >> $GITHUB_STEP_SUMMARY
