name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Prerequisites
      description: Please check the following before submitting
      options:
        - label: I have searched the [existing issues](https://github.com/stacksjs/craft/issues) and this bug has not been reported
          required: true
        - label: I have read the [documentation](https://github.com/stacksjs/craft/tree/main/docs)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a new project with `bun create craft my-app`
        2. Run `craft run`
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) are affected?
      multiple: true
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (x86_64)
        - Linux (ARM64)
        - Windows (x86_64)
        - iOS
        - Android
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of the OS are you running?
      placeholder: "e.g., macOS 14.2, Ubuntu 22.04, Windows 11"
    validations:
      required: true

  - type: input
    id: craft-version
    attributes:
      label: Craft Version
      description: What version of Craft are you using?
      placeholder: "e.g., 0.0.1 or commit hash"
    validations:
      required: true

  - type: input
    id: zig-version
    attributes:
      label: Zig Version
      description: What version of Zig are you using?
      placeholder: "e.g., 0.15.1"
    validations:
      required: true

  - type: textarea
    id: minimal-reproduction
    attributes:
      label: Minimal Reproduction
      description: If possible, provide a minimal code example that reproduces the issue
      render: zig
      placeholder: |
        const craft = @import("craft");

        pub fn main() !void {
            // Minimal code to reproduce the bug
        }

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
