name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Prerequisites
      description: Please check the following before submitting
      options:
        - label: I have searched the [existing issues](https://github.com/stacksjs/craft/issues) and this feature has not been requested
          required: true
        - label: I have checked the [roadmap](https://github.com/stacksjs/craft/blob/main/TODO.md) and this is not already planned
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New API/functionality
        - Performance improvement
        - Developer experience (DX)
        - Documentation
        - Tooling (CLI, SDK)
        - Platform support
        - Component
        - Bridge/IPC
        - Plugin system
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear description of what the problem is. Ex. I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "A clear description of what you want to happen..."
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design (if applicable)
      description: If this involves new APIs, how would you like them to look?
      render: zig
      placeholder: |
        // Zig API example
        const window = try craft.Window.create(.{
            .title = "My App",
            .new_feature = true,
        });

        // Or TypeScript SDK
        // await craft.window.newFeature({ option: value });

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "Other approaches you've thought about..."

  - type: dropdown
    id: platforms
    attributes:
      label: Target Platforms
      description: Which platforms should this feature support?
      multiple: true
      options:
        - All platforms
        - Desktop only (macOS, Linux, Windows)
        - Mobile only (iOS, Android)
        - macOS
        - Linux
        - Windows
        - iOS
        - Android
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my use case
        - Blocking my adoption of Craft
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
        - label: I can help test this feature
        - label: I can help document this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request
