# Android Test Workflow
# Runs unit tests, instrumented tests, and lint checks
# Supports multiple API levels and device configurations

name: Android Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'android/**'
      - '.github/workflows/android-test.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'android/**'
  workflow_dispatch:
    inputs:
      api_level:
        description: 'Android API level'
        required: false
        default: '34'
      run_instrumented:
        description: 'Run instrumented tests'
        required: false
        default: 'true'
        type: boolean

env:
  JAVA_VERSION: '17'
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false"

jobs:
  lint:
    name: Lint & Static Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Run Lint
        run: |
          cd android
          ./gradlew lint

      - name: Upload Lint Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-results
          path: |
            android/app/build/reports/lint-results*.html
            android/app/build/reports/lint-results*.xml
          retention-days: 14

      - name: Run Detekt (if configured)
        continue-on-error: true
        run: |
          cd android
          if ./gradlew tasks --all | grep -q "detekt"; then
            ./gradlew detekt
          fi

      - name: Comment on PR with Lint Results
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request' && failure()
        with:
          script: |
            const fs = require('fs');
            const lintReport = 'android/app/build/reports/lint-results-debug.xml';
            if (fs.existsSync(lintReport)) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '⚠️ Lint checks found issues. Please review the artifacts for details.'
              });
            }

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Run Unit Tests
        run: |
          cd android
          ./gradlew testDebugUnitTest

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: |
            android/app/build/reports/tests/
            android/app/build/test-results/
          retention-days: 14

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'android/app/build/test-results/**/TEST-*.xml'
          check_name: 'Unit Test Results'
          fail_on_failure: true

      - name: Generate Coverage Report
        run: |
          cd android
          ./gradlew jacocoTestReport || true

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: coverage-report
          path: android/app/build/reports/jacoco/
          retention-days: 14

  instrumented-tests:
    name: Instrumented Tests (API ${{ matrix.api-level }})
    runs-on: ubuntu-latest
    timeout-minutes: 45
    needs: unit-tests

    strategy:
      fail-fast: false
      matrix:
        include:
          - api-level: 34
            target: google_apis
            arch: x86_64
          - api-level: 31
            target: google_apis
            arch: x86_64
          - api-level: 28
            target: google_apis
            arch: x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.target }}-${{ matrix.arch }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated AVD snapshot for caching"

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            cd android
            ./gradlew connectedDebugAndroidTest

      - name: Upload Instrumented Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: instrumented-test-results-api${{ matrix.api-level }}
          path: |
            android/app/build/reports/androidTests/
            android/app/build/outputs/androidTest-results/
          retention-days: 14

      - name: Publish Instrumented Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'android/app/build/outputs/androidTest-results/**/*.xml'
          check_name: 'Instrumented Test Results (API ${{ matrix.api-level }})'
          fail_on_failure: true

  screenshot-tests:
    name: Screenshot Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Screenshot Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: |
            cd android
            ./gradlew verifyPaparazziDebug || ./gradlew recordPaparazziDebug

      - name: Upload Screenshot Differences
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshot-differences
          path: |
            android/app/build/paparazzi/
            android/app/out/failures/
          retention-days: 14

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, instrumented-tests]
    if: always()

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate Summary
        run: |
          echo "## Android Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### Jobs Status" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Lint | ${{ needs.lint.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Unit Tests | ${{ needs.unit-tests.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Instrumented Tests | ${{ needs.instrumented-tests.result }} |" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Test Artifacts" >> $GITHUB_STEP_SUMMARY

          if [ -d "artifacts" ]; then
            find artifacts -type f -name "*.xml" -o -name "*.html" | head -20 | while read f; do
              echo "- $f" >> $GITHUB_STEP_SUMMARY
            done
          fi

      - name: Check for failures
        if: needs.lint.result == 'failure' || needs.unit-tests.result == 'failure' || needs.instrumented-tests.result == 'failure'
        run: |
          echo "❌ Some tests failed. Please review the artifacts for details."
          exit 1
